### PR TITLE
Bump marge-bot version to 0.9.5

### PR DESCRIPTION
**Pull request by JanMikes**
Hi @zhilyaev im not sure if index.yaml should be updated too or Chart.yaml is enough.

### CODE REVIEW

**Comment by zhilyaev** [comment]
Thanks for your bump! @JanMikes 
index.yaml allows use git as helm-repo.
I think better will be that:

```yaml
image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
```
for line at
https://github.com/zhilyaev/marge-bot-helm/blob/3a887ac49659022cc35407d7a30d0b03b5b376b1/templates/deployment.yaml#L27

and set appVersion as latest maybe...

**Comment by JanMikes** [comment]
Yeah, i have been thinking about :latest as well and i like it, but i think that could be a bc break. If you are opened to that i will do it and set image tag to `:latest` :-)

**Comment by JanMikes** [comment]
I think that these lines should be updated as well but im not sure what to put there:
https://github.com/zhilyaev/marge-bot-helm/blob/3a887ac49659022cc35407d7a30d0b03b5b376b1/index.yaml#L23-L25

**Review by zhilyaev — APPROVED** [review]

**Comment by zhilyaev** [comment]
index.yaml needs delete and use #2 .

**Comment by MaxWinterstein** [comment]
This was never released to the public, right?

```bash
$ helm search repo marge 
NAME            CHART VERSION   APP VERSION     DESCRIPTION                        
marge/marge-bot 1.1.0           0.9.2           Marge-bot is a merge-bot for GitLab
```

**Comment by MaxWinterstein** [comment]
This was never released to the public, right?

```bash
$ helm search repo marge 
NAME            CHART VERSION   APP VERSION     DESCRIPTION                        
marge/marge-bot 1.1.0           0.9.2           Marge-bot is a merge-bot for GitLab
```

**Pull request merged**
